### ISSUE TITLE
Using AlertsApi.alerts.get returns 'admiralty_code' error 

### ISSUE THREAD

**Issue by ghost** [intel471/titan-client-python#1]
Hello, I have encountered an error when using the alerts method in `titan-client`, what could be happening?

**Code**:

```
  with titan_client.ApiClient(conf) as api_client:
        # Create an instance of the API class
        api_instance = titan_client.AlertsApi(api_client)
        # conf alerts
        ....

        try:
            api_response = api_instance.alerts_get(params)
            return api_response
        except ApiException as e:
            print("Exception when calling AlertsApi->alerts_get: %s\n" % e)
```

**ValueError**:

```
    raise ValueError("Invalid value for `admiralty_code`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `admiralty_code`, must not be `None`
```

Thank you.

**Comment by mmolenda** [comment]
Thank you for reporting the issue. It is now solved in [v1.16.1.1](https://github.com/intel471/titan-client-python/releases/tag/v1.16.1.1).

**Comment by ghost** [comment]
Still happening with v.1.16.1.1 with same code.

**Comment by ghost** [comment]
Can we confirm that this has been solved? @mmolenda thanks.

**Comment by mmolenda** [comment]
Hi, can you please send an email to ***@***.*** and provide more
details on your request please? Especially the username and query params.

Thanks
Marcin Molenda

pon., 20 wrz 2021, 19:19 użytkownik Juan A. Velasco <
***@***.***> napisał:

**Comment by mmolenda** [comment]
Sorry, I was responding using email and I just realised the email address I provided was obfuscated.
Please contact support at https://intel471.com/company/contact. Thanks.
