### ISSUE TITLE
PyYAML, and requirements regression in release 1.19.8

### ISSUE THREAD

**Issue by parry-jack** [intel471/titan-client-python#28]
Fixed

_Originally posted by @mmolenda in https://github.com/intel471/titan-client-python/issues/23#issuecomment-1699295885_
            

Hello, looks like release [Release v1.19.8](https://github.com/intel471/titan-client-python/commit/b62f171bed92d184f0419fe04fad5272e8ac04f2) introduced a regression in requirements.txt, nullifying this change (and making anything using this upstream now pinned at the regressed version).

**Comment by mmolenda** [comment]
Fixed in https://github.com/intel471/titan-client-python/pull/29. Fixed also in build script so it will not reoccur in the future. 
Thank you for reporting.

**Comment by mmolenda** [comment]
Done
